### ISSUE TITLE
Release Version 2.3.0

### ISSUE THREAD

**Issue by neersighted** [MitMaro/git-interactive-rebase-tool#848]
Hi, is it possible to get a release with https://github.com/MitMaro/git-interactive-rebase-tool/pull/801 + the additional PRs merged in the last 6 months? Thanks!

---

Release checklist:

- [x] Update the release workflows to include the latest versions of Ubuntu, Debian (#854)
- [x] Test on Windows
- [x] Test on macOS
- [x] Test on Linux
- [x] Update CHANGELOG (https://github.com/MitMaro/git-interactive-rebase-tool/pull/867)
- [x] Bump `Cargo.toml` version number (https://github.com/MitMaro/git-interactive-rebase-tool/pull/868)
- [x] Release crates to crates.io
- [x] Tag new release tag

Known issues:
- [x] Events in Windows are "duplicated", causing broken functionality (#864)
- [x] #837 
- [x] External editor not loading (#866)

After release checklist:

- [x] Update README to add reference to development build
- [x] Fix changelog date
- [x] Fix release script order

**Comment by MitMaro** [comment]
Sadly, I've been on a bit of a hiatus since early in the year. I agree, a new release is badly needed.

I have one bug to address, then I can test on the platforms I test, and get a new release out.

Thanks for the bump/reminder on the release, and apologies that it has taken this long to respond.

**Comment by MitMaro** [comment]
🎉 Version 2.3.0 has been published. Various third-party distributors (i.e. homebrew) should pick up the release in the next day or two.

Thanks again for the friendly bump!

**Comment by neersighted** [comment]
https://github.com/Homebrew/homebrew-core/pull/137013 😇
