### ISSUE TITLE
Release Version 2.4.0

### ISSUE THREAD

**Issue by MitMaro** [MitMaro/git-interactive-rebase-tool#915]
Release checklist:

- [x] Update README to remove reference to development build (#921)
- [x] Update the release workflows to include the latest versions of Ubuntu, Debian (#917)
- [x] Test on Windows
- [x] Test on macOS
- [x] Test on Linux
- [x] Update CHANGELOG (#914)
- [x] Bump `Cargo.toml` version number (#922)
- [x] Release crates to crates.io ([v2.4.0](https://crates.io/crates/git-interactive-rebase-tool/2.4.0))
- [x] Tag new release tag ([v2.4.0](https://github.com/MitMaro/git-interactive-rebase-tool/releases/tag/2.4.0))

Known Bugs:

- [x] Last line hidden behind search bar (#919)
- [x] Visual mode only ensures last-selected line is visible (#918)

After release checklist:

- [x] Update README to add reference to development build (#924)
- [x] Fix changelog date (#924)

**Comment by MitMaro** [comment]
Documentation updates needed:

- Instructions on building RPM
- Remove stated support for Windows 8
